### PR TITLE
Add suggest_url

### PR DESCRIPTION
**Pull request by Mixaz017**
This will allow users to see search suggestions if suggestions are enabled on their end.

### CODE REVIEW

**Comment by actionless** [comment]
thanks for your contribution!

have you already tested your patch of the extension with firefox-dev?

**Comment by Mixaz017** [comment]
Not with the dev edition, but I have tested this with the latest Firefox and it works nicely. I can install and test with the dev edition if needed.
image

**Comment by actionless** [comment]
that's ok - that api shouldn't change in next version as far as i see

thanks again! :)

please remind me to release it if i wont do it til tmrw morning

**Comment by Mixaz017** [comment]
Thank you for accepting the PR!
I didn't know when is tomorrow morning for your timezone, but the addon page still says updated 2 years ago so I'm here to remind you. (or does Mozilla just takes time to review the extension? I have no experience with publishing extensions)

**Comment by actionless** [comment]
thanks, just published the update!
usually it ger reviewed within 10-ish minutes

**Pull request merged**
